### ISSUE TITLE
Looking for dataset

### ISSUE THREAD

**Issue by gopalmenon** [georgesung/ml_competition_didi#1]
I could not find a way to download the train and test data from the Didi website. I realize the competition is over, but was interested in working on the problem. Do you have the data any place that I could get access to? Thanks!!!

**Comment by georgesung** [comment]
I just checked http://research.xiaojukeji.com/competition/detail.action?competitionId=DiTech2016, unfortunately it looks like the dataset download link does not work anymore. I also reformatted my hard drive so I lost my local copy of the data as well =\

**Comment by gopalmenon** [comment]
Thanks for your quick response.
